#!/usr/bin/env bash
# Run @dist.name@ in JVM mode on aarch64.
set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SCRIPT_SOURCE" ]; do
  SCRIPT_DIR=$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)
  SCRIPT_SOURCE=$(readlink "$SCRIPT_SOURCE")
  [[ $SCRIPT_SOURCE != /* ]] && SCRIPT_SOURCE="$SCRIPT_DIR/$SCRIPT_SOURCE"
done
SCRIPT_DIR=$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)
LIB_DIR="$SCRIPT_DIR/../lib"

MODULE_PATH="$(ls "$LIB_DIR"/*.jar | tr '\n' ':')"
exec java \
    --module-path "$MODULE_PATH" \
    --enable-native-access=javafx.graphics \
    --enable-preview \
    -m @dist.module@/@dist.main.class@ "$@"
